from pyglet.window import key

FPS = 75
GAME_TITLE = "POC"
PLAYER_MOVE_DOWN_KEY = key.S
PLAYER_MOVE_LEFT_KEY = key.A
PLAYER_MOVE_RIGHT_KEY = key.D
PLAYER_MOVE_UP_KEY = key.W
PLAYER_SPEED = 200
WINDOW_HEIGHT = 600
WINDOW_WIDTH = 800
